### PR TITLE
Remove navigation requirement from contributing.md

### PR DESCRIPTION
**Pull request by nottrobin**
We no longer need the navigation section

### CODE REVIEW

**Comment by anthonydillon** [comment]
Would you mind fixing the CI issue introduced by #238 for bonus points?

**Comment by nottrobin** [comment]
@anthonydillon how did that get merged? I'm gonna make the prettier check required unless you object.

**Comment by anthonydillon** [comment]
It was merged by Claudio as he didn't know the process. The check should of course be required.

**Comment by anthonydillon** [comment]
I've made the checks required

**Comment by clagom** [comment]
Sorry! @nottrobin @anthonydillon

**Comment by anthonydillon** [comment]
@clagom not your fault. The system shouldn't have let you make a mistake.

**Comment by nottrobin** [comment]
@anthonydillon I switched over to github actions at the same time =)

**Pull request merged**
